user nginx;
worker_processes auto;
pid /var/run/nginx.pid;

events {
    worker_connections 768;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    access_log /dev/stdout combined;
    error_log /dev/stderr info;
    sendfile on;
    keepalive_timeout 65;

    upstream gatekeeper {
        server unix:/var/run/gatekeeper/gatekeeper.sock;
    }

    server {
        listen 80;
        server_name localhost;

        # Internal Gatekeeper Auth Facade
        location = /gatekeeper {
            internal;
            proxy_pass http://gatekeeper/auth/check;
            
            proxy_pass_request_body off;
            proxy_set_header Content-Length "";
            
            proxy_set_header X-Original-IP $remote_addr;
            proxy_set_header X-Original-Host $host;
            proxy_set_header X-Original-URI $request_uri;
            
            proxy_set_header X-TLS-Protocol $ssl_protocol;
            proxy_set_header X-TLS-Cipher $ssl_cipher;

            proxy_set_header X-Http-Lang $http_accept_language;
            proxy_set_header X-Http-Enc $http_accept_encoding;
            proxy_set_header User-Agent $http_user_agent;
        }

        # Verification form endpoint (GET renders form, POST validates challenge & sets cookie)
        location = /verify-request {
            proxy_pass http://gatekeeper/auth/verify;

            proxy_set_header X-Original-IP $remote_addr;
            proxy_set_header X-Original-Host $host;
            proxy_set_header X-Original-URI $request_uri;
            
            proxy_set_header X-TLS-Protocol $ssl_protocol;
            proxy_set_header X-TLS-Cipher $ssl_cipher;

            proxy_set_header X-Http-Lang $http_accept_language;
            proxy_set_header X-Http-Enc $http_accept_encoding;
            proxy_set_header User-Agent $http_user_agent;
        }
        
        location = / {
            auth_request /gatekeeper;
            error_page 401 =200 /verify-request;

            # Hand over to the internal granted content after auth_request succeeds
            try_files /_dummy @granted;
        }
        
        # Internal target served upon valid auth pass
        location @granted {

            default_type text/plain;
            return 200 "Cookie accepted: Access granted!";
        }

        # Live Metrics (for showcase only)
        location = /live-metrics {
            proxy_pass http://gatekeeper/auth/metrics;
        }

        # Honeypot
        location ^~ /x/data {
            proxy_pass http://gatekeeper/honeypot;
    
            proxy_set_header X-Original-IP $remote_addr;
            proxy_set_header X-Original-Host $host;
            proxy_set_header X-Original-URI $request_uri;
            
            proxy_set_header User-Agent $http_user_agent;
            
            limit_rate 2k;
        }
    }
}
