# Copy this snippet to Nginx's configuration directory (e.g., /etc/nginx/snippets/gatekeeper/honeypot.conf;)
# and include it inside your main server block (e.g., include snippets/gatekeeper/honeypot.conf;)

# Scraper Honeypot
location ^~ /x/data {
    proxy_pass http://gatekeeper/honeypot;
    
    proxy_set_header X-Original-IP $remote_addr;
    proxy_set_header X-Original-Host $host;
    proxy_set_header X-Original-URI $request_uri;
    
    proxy_set_header User-Agent $http_user_agent;
    
    limit_rate 2k;
}
