# Copy this snippet to Nginx's configuration directory (e.g., /etc/nginx/snippets/gatekeeper/upstream.conf;)
# and include it inside your main server block (e.g., include snippets/gatekeeper/upstream.conf;)

# Central Gatekeeper Upstream
upstream gatekeeper {
    server unix:/var/run/gatekeeper/gatekeeper.sock;
}
